/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  providerSidebar: [
    {
      id: 'intro',
      type: 'doc',
    },
    {
      collapsed: false,
      type: 'category',
      label: 'Add Your Project',
      link: {
        type: 'doc',
        id: 'providers/intro',
      },
      items: [
        {
          type: 'doc',
          id: 'providers/intro',
        },
        {
          type: 'doc',
          id: 'providers/bridge'
        },
        {
          type: 'category',
          label: '2. Identity Pipeline',
          link: {
            type: 'doc',
            id: 'providers/pipeline/intro',
          },
          items: [
            'intro',
            'web3',
            'oauth',
            'iframe',
            'transform',
            'select',
            'custom',
            'context',
            'errors',
          ]
            .map(id => ({ id: `providers/pipeline/${id}`, type : 'doc' }))
            .concat([
              {
                collapsed: false,
                type: 'category',
                label: 'Example Pipelines',
                items: [
                  {
                    type: 'link',
                    href: 'https://github.com/AvatarConnect/bridge/blob/0c0a3c00749d26ab79ba2a2a18adf2d5c924af9a/providers/ReadyPlayerMe/index.js#L15',
                    label: 'ReadyPlayerMe',
                  },
                  {
                    type: 'link',
                    href: 'https://github.com/AvatarConnect/bridge/blob/0c0a3c00749d26ab79ba2a2a18adf2d5c924af9a/providers/Meebits/index.js#L42',
                    label: 'Meebits',
                  },
                  {
                    type: 'link',
                    href: 'https://github.com/AvatarConnect/bridge/blob/0c0a3c00749d26ab79ba2a2a18adf2d5c924af9a/providers/CryptoAvatars/index.js#L13',
                    label: 'CryptoAvatars',
                  }
                ]
              }
            ])
        },
        {
          type: 'doc',
          id: 'providers/testing',
        },
        {
          type: 'doc',
          id: 'providers/submit',
        }
      ],
    },
  ]
};

module.exports = sidebars;